import Columns from '../columns';
import ColumnsInterface from '../interfaces/columns';

class AccountsCols extends Columns implements ColumnsInterface {
    constructor() {
        super();

        this.select = ['account_id','account_class','account_status','account_type','account_login','account_code','account_full','account_email','account_phone','account_zip','account_photo','account_crypt','account_hash','account_lat','account_lon','account_nonce','account_dob','account_createdon','account_updatedon'];
        this.insert = ['account_id','account_class','account_status','account_type','account_login','account_code','account_full','account_email','account_phone','account_zip','account_photo','account_crypt','account_hash','account_lat','account_lon','account_nonce','account_dob','account_createdon','account_updatedon'];
        this.update = ['account_id','account_class','account_status','account_type','account_login','account_code','account_full','account_email','account_phone','account_zip','account_photo','account_crypt','account_hash','account_lat','account_lon','account_nonce','account_dob','account_createdon','account_updatedon'];
        this.exact = ['account_id','account_class','account_status','account_type','account_login','account_code','account_full','account_email','account_phone','account_zip','account_photo','account_crypt','account_hash','account_lat','account_lon','account_nonce','account_dob','account_createdon','account_updatedon'];
        this.search = ['account_id','account_class','account_status','account_type','account_login','account_code','account_full','account_email','account_phone','account_zip','account_photo','account_crypt','account_hash','account_lat','account_lon','account_nonce','account_dob','account_createdon','account_updatedon'];

        this.guids = ['account_id'];
        this.strings = ['account_id','account_class','account_status','account_type','account_login','account_code','account_full','account_email','account_phone','account_zip','account_photo','account_crypt','account_hash'];
        this.dates = ['account_dob','account_createdon','account_updatedon'];
        this.booleans = [];
        this.numbers = ['account_lat','account_lon','account_nonce'];
        
        this.primary = 'account_id';
        this.sortcol = 'account_updatedon';
        this.sortdir = 'desc';
        this.sortorder = 'account_updatedon desc';

        this.aliases = 	{
            admin_id: "account_id",
            admin_full: "account_full",
            admin_email: "account_email",
            admin_phone: "account_phone",
            admin_photo: "account_photo",
            agent_id: "account_id",
            agent_full: "account_full",
            agent_email: "account_email",
            agent_phone: "account_phone",
            agent_photo: "account_photo",
            approver_id: "account_id",
            approver_full: "account_full",
            approver_email: "account_email",
            approver_phone: "account_phone",
            approver_photo: "account_photo",
            author_id: "account_id",
            author_full: "account_full",
            author_email: "account_email",
            author_phone: "account_phone",
            author_photo: "account_photo",            
            contact_id: "account_id",
            contact_class: "account_class",
            contact_status: "account_status",
            contact_first: "account_first",
            contact_last: "account_last",
            contact_full: "account_full",
            contact_email: "account_email",
            contact_phone: "account_phone",
            contact_photo: "account_photo",
            contact_qr: "account_qr",
            contact_dob: "account_dob",
            contact_type: "account_type",
            contact_country: "account_country",
            contact_zip: "account_zip",
            creator_id: "account_id",
            creator_full: "account_full",
            creator_email: "account_email",
            creator_phone: "account_phone",
            creator_photo: "account_photo",
            customer_id: "account_id",
            customer_full: "account_full",
            customer_email: "account_email",
            customer_phone: "account_phone",
            customer_photo: "account_photo",
            editor_id: "account_id",
            editor_full: "account_full",
            editor_email: "account_email",
            editor_phone: "account_phone",
            editor_photo: "account_photo",            
            group_id: "account_id",
            group_full: "account_full",
            group_email: "account_email",
            group_phone: "account_phone",
            group_photo: "account_photo",            
            issuer_id: "account_id",
            issuer_class: "account_class",
            issuer_status: "account_status",
            issuer_login: "account_login",
            issuer_first: "account_first",
            issuer_last: "account_last",
            issuer_full: "account_full",
            issuer_email: "account_email",
            issuer_phone: "account_phone",
            issuer_photo: "account_photo",
            issuer_zip: "account_zip",
            issuer_currency: "account_currency",
            issuer_level: "account_level",
            manager_id: "account_id",
            manager_full: "account_full",
            manager_email: "account_email",
            manager_phone: "account_phone",
            manager_photo: "account_photo",
            owner_id: "account_id",
            owner_full: "account_full",
            owner_email: "account_email",
            owner_phone: "account_phone",
            owner_photo: "account_photo",
            partner_id: "account_id",
            partner_full: "account_full",
            partner_email: "account_email",
            partner_phone: "account_phone",
            partner_photo: "account_photo",
            payee_id: "account_id",
            payee_class: "account_class",
            payee_status: "account_status",
            payee_login: "account_login",
            payee_first: "account_first",
            payee_last: "account_last",
            payee_full: "account_full",
            payee_email: "account_email",
            payee_phone: "account_phone",
            payee_photo: "account_photo",
            payee_zip: "account_zip",
            payee_currency: "account_currency",
            payee_level: "account_level",
            recipient_id: "account_id",
            recipient_full: "account_full",
            recipient_email: "account_email",
            recipient_phone: "account_phone",
            recipient_photo: "account_photo",
            requestor_id: "account_id",
            requestor_full: "account_full",
            requestor_email: "account_email",
            requestor_phone: "account_phone",
            sender_id: "account_id",
            sender_full: "account_full",
            sender_email: "account_email",
            sender_phone: "account_phone",
            sender_photo: "account_photo",
            sponsor_id: "account_id",
            sponsor_login: "account_login",
            sponsor_full: "account_full",
            sponsor_email: "account_email",
            sponsor_phone: "account_phone",
            sponsor_photo: "account_photo",
            technician_id: "account_id",
            technician_full: "account_full",
            technician_email: "account_email",
            technician_phone: "account_phone",
            technician_login: "account_login",
            technician_photo: "account_photo",
            vendor_id: "account_id",
            vendor_full: "account_full",
            vendor_email: "account_email",
            vendor_phone: "account_phone",
            vendor_photo: "account_photo",
        };        
    }
}
export default AccountsCols;